# -*- coding: utf-8 -*-
"""Material_names.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OmKJ4GIUPzXntEnKXR7m21hO4uN6V1BP
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

url ="https://www.efunda.com/materials/polymers/history/history.cfm?list_order=name"
r=requests.get(url)
print(r.status_code)

soup = BeautifulSoup(r.text, 'html.parser')
print(soup)

!pip install inscriptis

from inscriptis import get_text

html = urllib.request.urlopen(url).read().decode('utf-8')
text = get_text(html)
print(text)

mat = urllib.request.urlopen(url).read().decode('utf-8')
mat_data = get_text(mat)
print(mat_data)

table_data = soup.find_all("table", align="center")
#print(table_data)

for row in table_data:
  data_entity=[]
  mat_name = row.find("tr").text.strip()
  data_entity.append(mat_name)
  table_data = row.find_all("tr", align ="left")
  for each in table_data:
    data_entity.append(each.text)
  print(data_entity)







